### PR TITLE
84 vagrant provisioning issues

### PR DESCRIPTION
**Pull request by bmathews**
- The base ubuntu box we're using doesn't have git installed. This installs it, which is necessary for some npm/bower functionality.
- Added NFS for faster fs perf
- Improved network performance/reliability
- Increased default ram/cpu allocation to prevent out of memory errors during compilation of native deps

@Ken-2scientists, @darthtrevino, @natoverse, @stopyoukid

### CODE REVIEW

**Comment by bmathews** [comment]
It was preventing npm install from working correctly.

**Comment by bmathews** [comment]
@Ken-2scientists Looks like using dhcp instead of a static ip works too.

**Comment by natoverse** [comment]
:shipit:

**Comment by darthtrevino** [comment]
:shipit: 
can you add ssh-agent forwarding? 
```
# SSH Agent Forwarding
env.ssh.forward_agent = true
```

**Comment by darthtrevino** [comment]
This is a personal preference, but I like having zsh being set as my default shell with oh-my-zsh addons installed. If you look in the retrace repos, I have salt states for doing that. Is vim or emacs installed by default in the virtualbox?

**Pull request merged**
